[package]
name = "plonky2_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2 = "0.1.3"
anyhow = { version = "1.0.40", default-features = false }